SET search_path = "courses";

INSERT INTO PERSON(ID, FIRSTNAME, LASTNAME) VALUES (1, 'Erhard', 'Siegl');
INSERT INTO PERSON(ID, FIRSTNAME, LASTNAME) VALUES (2, 'Thomas', 'Herzog');
INSERT INTO PERSON(ID, FIRSTNAME, LASTNAME) VALUES (3, 'Andreas', 'Mayer');
INSERT INTO PERSON(ID, FIRSTNAME, LASTNAME) VALUES (4, 'Egor', 'Erofeev');

INSERT INTO COURSE(ID, NAME, TEACHER_ID) VALUES (1, 'JBoss Training', 1);
INSERT INTO COURSE(ID, NAME, TEACHER_ID) VALUES (2, 'Git Training', 2);

INSERT INTO COURSE_PARTICIPATION(PERSON_ID, COURSE_ID) VALUES (3, 1);
INSERT INTO COURSE_PARTICIPATION(PERSON_ID, COURSE_ID) VALUES (4, 1);
INSERT INTO COURSE_PARTICIPATION(PERSON_ID, COURSE_ID) VALUES (3, 2);